### ISSUE TITLE
tabix multipule regions with delimited between output regions

### ISSUE THREAD

**Issue by ekushele** [samtools/tabix#30] opened 2020-07-15 17:18 UTC
Hi,

Say I have a bed file, `file.bed`, and I want to retrieve multipule regions.
file.bed:
```
chr1    10468   10469   
chr1    10470   10471   
chr1    10483   10484   
chr1    10488   10489   
chr1    10492   10493   
chr1    10496   10497 
```

running `tabix file.bed  chr1:10468-10490 chr1:10478-10490 chr1:10496-10497` gives me all the rows that matches region in the `file.bed`:
```
chr1    10468   10469  
chr1    10470   10471  
chr1    10483   10484  
chr1    10488   10489  
chr1    10483   10484  
chr1    10488   10489 
chr1    10496   10497 
```
 
Can I have an option to separate between the results, i.e. to define which rows came from each region? Something like:
```
chr1    10468   10469  
chr1    10470   10471  
chr1    10483   10484  
chr1    10488   10489
  
chr1    10483   10484  
chr1    10488   10489 

chr1    10496   10497 
```

**Comment by valeriuo** [comment] 2020-07-16 06:38
Duplicate of https://github.com/samtools/htslib/issues/1107

**Closed by valeriuo** 2020-07-16 06:38 UTC
